name: BookInfo CI/CD with Istio

on:
  push:
    branches:
      - main

env:
  MINIKUBE_IP: $(minikube ip)

jobs:
  setup-minikube:
    name: Setup Minikube & Istio
    runs-on: self-hosted
    needs: [cleanup]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Start Minikube
        run: |
          if ! minikube status; then
            echo "Starting Minikube..."
            #minikube delete
            #minikube start --cpus=4 --memory=8192 --kubernetes-version=v1.30.0 --driver=virtualbox
            minikube start --cpus=4 --memory=8192 --disk-size=50g --kubernetes-version=v1.28.3 --driver=virtualbox
            #minikube start 
          else
            echo "Minikube is already running."
          fi
      - name: Check if Istio is Installed
        shell: bash
        run: |
          if istioctl x precheck; then
            echo "Istio is already installed."
          else
            echo "Istio is not installed. Installing Istio..."
            curl -L https://istio.io/downloadIstio | ISTIO_VERSION=1.25.0 sh -
            export PATH=$HOME/.istioctl/bin:$PATH
      
            istioctl install --set profile=demo -y
            kubectl label namespace default istio-injection=enabled




            echo "****************  http://$GATEWAY_URL/productpage   ********************"
            istioctl x precheck

          fi

  Minikube_IP:
    runs-on: self-hosted
    needs: setup-minikube
    steps:
      - name: Get Minikube IP
        shell: bash
        
        run: |
          export MINIKUBE_IP=$(minikube ip)
          echo "Minikube IP: $MINIKUBE_IP"  

  Install_Istio:
    runs-on: self-hosted
    needs: setup-minikube
    steps:
      - name: Check if Istio version
        shell: bash
        run: |
          export PATH=$HOME/.istioctl/bin:$PATH 
          if istioctl x precheck; then
            echo "Istio is already installed."
            istioctl x precheck
          else
            echo "Istio is not installed"
          fi

  Deploy_BookInfo:
    runs-on: self-hosted
    needs: [setup-minikube,check-istio, Install_Istio,check-istio, Minikube_IP, Install_Istio, infra-check]
    steps:
      - name: Deploy BookInfo App
        run: |
          kubectl label namespace default istio-injection=enabled
          kubectl apply -f bookinfo.yaml
          kubectl apply -f bookinfo-gateway.yaml
          kubectl rollout status deployment/productpage-v1 -n default --timeout=120s

  check-istio:
    name: Check Istio Status
    runs-on: self-hosted
    needs: setup-minikube
    steps:
      - name: Verify Istio Installation
        shell: bash
        run: |  
          export PATH=$HOME/.istioctl/bin:$PATH 
          istioctl x precheck

  deploy-monitoring:
    name: Deploy Monitoring (Grafana, Prometheus, Kiali)
    runs-on: self-hosted
    needs: [Deploy_BookInfo]
    steps:
      - name: Deploy Monitoring Services
        run: |
          kubectl get namespace istio-system || kubectl create namespace istio-system
          kubectl apply -f moniter/
          kubectl rollout status deployment/grafana -n istio-system --timeout=120s
          kubectl rollout status deployment/prometheus -n istio-system --timeout=120s
          kubectl rollout status deployment/kiali -n istio-system --timeout=120s

          export INGRESS_HOST=$(minikube ip)
          export INGRESS_PORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="http2")].nodePort}')
          export GATEWAY_URL=$INGRESS_HOST:$INGRESS_PORT
          echo "productpage : http://$GATEWAY_URL/productpage"

  monitor-grafana:
    name: Monitor Grafana
    runs-on: self-hosted
    needs: [deploy-monitoring, Minikube_IP]
    steps:
      - name: Check Grafana URL
        shell: bash
        run: |
          GRAFANA_URL="http://localhost:3000"
          echo "Checking Grafana: $GRAFANA_URL"
        #  curl -s --head --fail "$GRAFANA_URL" || exit 1

  monitor-jaeger:
    name: Monitor Jaeger
    runs-on: self-hosted
    needs: [deploy-monitoring, Minikube_IP]
    steps:
      - name: Check Jaeger URL
        shell: bash
        run: |
          JAEGER_URL="http://localhost:16686"
          echo "Checking Jaeger: $JAEGER_URL"
        #  curl -s --head --fail "$JAEGER_URL" || exit 1

  monitor-prometheus:
    name: Monitor Prometheus
    runs-on: self-hosted
    needs: [deploy-monitoring, Minikube_IP]
    steps:
      - name: Check Prometheus URL
        shell: bash
        run: |

          PROMETHEUS_URL="http://localhost:9090"
          echo "Checking Prometheus: $PROMETHEUS_URL"
        # curl -s --head --fail "$PROMETHEUS_URL" || exit 1

  monitor-kiali:
    name: Monitor Kiali
    runs-on: self-hosted
    needs: [deploy-monitoring, Minikube_IP]
    steps:
      - name: Check Kiali URL
        shell: bash
        run: |
          KIALI_URL="http://localhost:20001"
          echo "Checking Kiali: $KIALI_URL"
         # curl -s --head --fail "$KIALI_URL" || exit 1

  infra-check:
    name: Infrastructure Check
    runs-on: self-hosted
    needs: [setup-minikube, check-istio, Install_Istio]
    steps:
      - name: Check Infrastructure
        shell: bash
        run: |
          export PATH=$HOME/.istioctl/bin:$PATH 
          kubectl get nodes
          kubectl get pods -A
          echo "Kubernetes Version:"
          kubectl version
          echo "Minikube Version:"
          minikube version
          echo "istioctl x precheck:"
          istioctl x precheck
  security-scan:
    name: Trivy Security Scanning
    runs-on: self-hosted
    needs: [setup-minikube, infra-check]
    steps:
      - name: Check if Trivy is Installed
        shell: bash
        run: |
          # Define the images to scan
          # "istio/examples-bookinfo-reviews-v2:1.20.2"
          # "istio/examples-bookinfo-reviews-v3:1.20.2"
          # "istio/examples-bookinfo-ratings-v1:1.20.2"
          # "istio/examples-bookinfo-reviews-v1:1.20.2"
          # "istio/examples-bookinfo-details-v1:1.20.2"
          images=(
            "istio/examples-bookinfo-productpage-v1:1.20.2"

          )
          # Loop over each image and run Trivy scan
          for image in "${images[@]}"; do
            echo "Scanning $image"
            trivy image $image
          done

  deployment-status:
    name: Check Deployment Status
    runs-on: self-hosted
    needs: [setup-minikube, Deploy_BookInfo, deploy-monitoring]
    steps:
      - name: Verify Gateway & BookInfo Deployment
        run: |
          echo "Productpage : http://${MINIKUBE_IP}/productpage"
          kubectl get gateway -n default
          kubectl get virtualservice -n default
          kubectl get pods -n default
  run-tests:
    name: Run Tests
    runs-on: self-hosted
    needs: Deploy_BookInfo
    steps:
      - name: Run Integration Tests
        run: |
          # Add commands to run your tests here
          echo "Productpage : http://${MINIKUBE_IP}/productpage"
          echo "Running integration tests..."

  notify:
    name: Email Notify Team
    runs-on: self-hosted
    needs: [monitor-grafana, monitor-jaeger, monitor-prometheus, monitor-kiali, infra-check, security-scan, deployment-status, run-tests]
    steps:
      - name: Send email Notification
        run: |
          echo "Job Status: ${{ job.status }}"
          echo "Repository: ${{ github.repository }}"
          echo "Commit Message: ${{ github.event.head_commit.message }}"
          echo "Commit Author: ${{ github.event.head_commit.author.name }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Job: ${{ github.job }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "Productpage : http://${MINIKUBE_IP}/productpage"


  cleanup:
    name: Cleanup Resources
    runs-on: self-hosted

    if: always()
    steps:

      - name: Start Minikube
        run: |
          if ! minikube status; then
            echo "Starting Minikube..."
            #minikube delete
            #minikube start --cpus=4 --memory=8192 --kubernetes-version=v1.30.0 --driver=virtualbox
            minikube start --kubernetes-version=v1.32.0
            #minikube start 
          else
            echo "Minikube is already running."
            kubectl delete all --all --namespace=default
            kubectl delete all --all -n istio-system

          fi

  deploy:
    name: Final Deployment Step
    runs-on: self-hosted
    needs: [notify, cleanup]
    steps:
      - name: Display Deployment URLs
        shell: bash
        run: |
          export MINIKUBE_IP=$(minikube ip)
          echo "BookInfo Deployment Successfully Completed!"
          echo "Grafana URL: http://localhost:3000"
          echo "Prometheus URL: http://localhost:9090"
          echo "Kiali URL: http://localhost:20001"
          echo "JAEGER_URL: http://localhost:16686"
          echo "Productpage : http://${MINIKUBE_IP}/productpage"

