name: Simple CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-1:
    runs-on: ubuntu-latest
    steps:
      - name: Echo in Build-1
        run: echo "Build-1 is running"

  build-2:
    runs-on: ubuntu-latest
    steps:
      - name: Echo in Build-2
        run: echo "Build-2 is running"

  build-3:
    runs-on: ubuntu-latest
    steps:
      - name: Echo in Build-3
        run: echo "Build-3 is running"

  integration-1:
    needs: build-1
    runs-on: ubuntu-latest
    steps:
      - name: Echo in Integration-1
        run: echo "Integration-1 is running"

  integration-2:
    needs: build-2
    runs-on: ubuntu-latest
    steps:
      - name: Echo in Integration-2
        run: echo "Integration-2 is running"

  lint:
    needs: [build-2, build-3]
    runs-on: ubuntu-latest
    steps:
      - name: Echo in Lint
        run: echo "Linting is running"

  unit-test:
    needs: build-3
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test: [1, 2, 3]
    steps:
      - name: Echo in Unit Test
        run: echo "Unit Test ${{ matrix.test }} is running"

  deploy:
    needs: [integration-1, integration-2, lint, unit-test]
    runs-on: ubuntu-latest
    steps:
      - name: Echo in Deploy
        run: echo "Deployment is running"
