name: Deploy BookInfo App with Istio

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted   # Your self-hosted runner name

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Start Minikube
        run: |
          minikube status    
          Gith#|| minikube start

      - name: Set up kubectl
        run: |
          kubectl cluster-info
          kubectl get nodes


      - name: Deploy BookInfo App
        run: |
          kubectl apply -f platform/kube/bookinfo.yaml
          kubectl apply -f networking/bookinfo-gateway.yaml

      - name: Verify Deployment
        run: |
          kubectl get pods -n default
          kubectl get svc -n default
          kubectl get gateways -n default
